### ISSUE TITLE
Als werknemer wil ik mijn profiel kunnen inzien zodat ik snel informatie en updates kan bekijken en weinig tijd krijt ben aan zoeken

### ISSUE THREAD

**Issue by justalana** [justalana/tle1-ontwerpen#10]
##DoD
- [x]  Werkt op verschillende browsers
- [x]  Is geschikt voor mobiele telefoon
- [x]  Voldoet aan de styleguide
- [x] Voldoet aan de code conventions
- [x] Routes en formulieren goed beveiligen
- [ ] Voldoet aan WACG level A

## Acceptatie criteria

- [x] - Informatie meegegeven op profiel is beperkt
- [x] - updates en meldingen zijn makkelijk terug te vinden

**Comment by AlexDusselaar** [comment]
zelfde feedback als user story 1 en 5, functionaliteit is helemaal goed maar de css moet nog even aangepast worden naar de style guide. heb het ook even met sander en esse besproken en het is misschien makkelijker om dat op een nieuwe pagina te doen om breeze components te omzeilen maar ik stel voor dat we daar later even naar kijken met een aantal mensen van het team.
