### ISSUE TITLE
Als werkgever wil ik een bevestigingsmail sturen zodat de kandidaten weten wat de volgende stappen zijn

### ISSUE THREAD

**Issue by justalana** [justalana/tle1-ontwerpen#19]

**Comment by AlexDusselaar** [comment]
DoD: Na acceptatie ontvangt de werkzoekende een e-mail met een link naar een pagina met details over de baan en de startdatum.
Accepatiecriteria: 
- Werkzoekenden zien een duidelijke samenvatting van de functie.
- via link in mail naar een pagina met meer info
-
