### ISSUE TITLE
Als werkgever wil ik mijn profiel kunnen inzien zodat ik snel informatie en updates kan inzien zonder veel tijd kwijt te zijn aan zoeken

### ISSUE THREAD

**Issue by justalana** [justalana/tle1-ontwerpen#21]
## Acceptatie criteria

- [x] - Informatie meegegeven op profiel is beperkt
- [x] - updates en meldingen zijn makkelijk terug te vinden

**Comment by AlexDusselaar** [comment]
Ik zou voor de vorm het blade bestand 'employer' noemen ipv 'employee' zodat dat matched met de rol, verder helemaal netjes :)
