### ISSUE TITLE
Als werkzoekende wil ik annoniem antwoord geven op een vacature met werktijden zodat ik snel een baan kan krijgen zonder dat bepaalde vooroordelen mij kunnen uitsluiten

### ISSUE THREAD

**Issue by Spooked2** [justalana/tle1-ontwerpen#22]
- [ ] werkdagen moeten kiesbaar zijn op vacature
- [x] controleer ingevulde gegevens van aanmelding voordat de vacature wordt opgestuurd
- [ ] geef optie voor edit in het geval dat er iets verkeerd is ingevuld
- [x] requirements worden opgeslagen in de juiste tabel en gelinkt aan de application
- [x] je wordt gestuurd naar een overzicht van je ingevulde vacature na het opsturen ervan

**Comment by Spooked2** [comment]
In de application controller op lijn 50 kan je beter een enter tussen de save en redirect zetten (die redirect kan ook met de functie to_route). Op lijn 42 heb je een stukje om de requirements te binden aan de application; die heb ik beter geschreven in story-9 in een enkele lijn met de sync() functie. Als je dat wil gebruiken kan dat ook.

RequirementApplication is nogsteeds niet in alfabetische volgorde. Weet niet of Laravel hierover gaat klagen, maar de conventie is wel om het op alfabetische volgorde te doen.

De props in je blade bestanden staan als array, dus die kan je beter zo schrijven: @props(['prop1', 'prop2'])

**Comment by AlexDusselaar** [comment]
apply.blade.php regel 12 staat do confirmation nog in het Engels, zou dat voor dat voor de consistency in het Nederlands zetten. Verder zou ik bij details.blade.php een redirect gooien op regel 26 en 32 in plaats van een h2, is net iets veiliger.

**Comment by Spooked2** [comment]
In de application controller staan nog een paar lijntjes code die zijn uitgecomment.

Hoewel het niet fout is, kan je ook in de view zelf vanuit de $application de requirements, user en andere dingen halen.
Wat wel een probleem is is dat je nu altijd de user pakt die nu is ingelogd. Dit kan problemen veroorzaken als de werkgever naar deze pagina moet gaan. Je gebruikt de user ook nog niet in de application detail view, en in die view staan ook nog wat comments. Je hebt ook geen titel toegevoegd aan de pagina.

In de gates onder create-application kan de employer nu ook een application aanmaken, dat hoort misschien niet?

in de de application.apply view staat ook nog geen titel. Geen super erg probleem, de standaard titel is "Open Hiring" en wordt gebruikt als er geen titel is meegegeven.

**Comment by Spooked2** [comment]
In de application controller staat nog een uit-gecommente dd() op lijn 56.

Hoewel het niet een super belangrijk probleem is, lijkt het mij wel handig als de user door een admin gekozen kan worden indien dit nodig is. Als je de user altijd uit de auth()->user haalt dan kan je in de problemen komen als iemand anders de application moet zien of aanmaken. 

Wat geen probleem is, gewoon een code keuze, lijkt het mij handiger om de application timeslots en dergelijke in de view pas aan te vragen.
 
De gate genaamd "show-application" zou misschien beter "view-application" heten, maar het zou beide kunnen.

Er staat nog een uit-gecommente dd in apply.blade.php.

De migration genaamd 'application_time_slot' kan beter "create_application_time_slot_table' heten. Niet dat dit problemen veroorzaakt, maar meer om de conventies aan te houden. In deze migration kan je ook makkelijker $table->foreignId() gebruiken, dat bespaard wat typwerk, al is wat je nu gedaan hebt niet fout. 

In de model ApplicationTimeSlot kan je 'extends model' vervangen met 'extends pivot'. Alweer conventies, hier gaat (denk ik) niks stuk van. Wat wel een probleem kan zijn zijn de $fillable en $casts, die zeggen namelijk dat er andere dingen in staan dan alleen een application id en een time slot id. hier staat ook dat die 'belongs to' een day, maar dat is niet direct zo, dus die kan er beter uit.
