### ISSUE TITLE
Als werkgever wil ik een vacature kunnen aanmaken, zodat ik nieuwe mensen kan aannemen

### ISSUE THREAD

**Issue by justalana** [justalana/tle1-ontwerpen#29]
Bij het aanmaken van een vacature kan ik een beschrijving, de contractduur, de werkuren, het salaris, de benodigde handelingen, de vereisten en de locatie van de baan aangeven

- [x] -  een beschrijving van in het vacature aanmaak formulier
- [x] - de tekst in de beschrijving kunnen formatteren
- [x] - de contractduur kunnen aangeven
- [x] - de werkuren kunnen aangeven
- [x] - het salaris kunnen aangeven
- [x] - een lijst met voorverzonen benodigde handelingen
- [x] - eigen benodigde handelingen kunnen aanvinken
- [x] - een lijst met voorverzonen benodigde handelingen
- [x] - eigen vereisten kunnen aanvinken
- [x] - de locatie kunnen aangeven in het formulier
- [x] - een knop voor het aanmaken van een vacature

**Comment by justalana** [comment]
ik zou ervoor zorgen dat in de formuliers die je hebt gemaakt dat het label voor de gebruiker in het nederlands is. Want vgm zei IO dat ook en dat we er altijd een vertaal systeem overheen kunnen gooien. Dus ook met je buttons  en pagina titels enzo in het nederlands doen

**Comment by AlexDusselaar** [comment]
Code ziet er helemaal netjes uit, enige dat ik zou aanpassen eventueel is de contractduur. Zou hem zelf in weken zetten in plaats van dagen maar dat moeten we ff met het team beslissen denk ik

**Comment by Esse03** [comment]
hij is een beetje wonky, als je naar het vak er onder klikt schiet ie weer naar boven
