### ISSUE TITLE
Contact pagina aanmaken

### ISSUE THREAD

**Issue by Zoruasy** [justalana/tle1-ontwerpen#35]

**Comment by justalana** [comment]
je kan de comments wel weglaten op de contact pagina, is handig als iets lastig is of ingewikkeld om te begrijpen, maar is hiervoor niet nodig

de div van regel 13-15 op de contact pagina moet nog een stukje naar rechts geschoven worden, want hij ziet nu niet de </p> tag, het geeft geen error maar is voor de code conventies wel belangrijk.

op regel 19 en 20 heb je de links nog in een p tag gezet, tenzij dat voor de styling belangrijk is kan je de p tags wel weghalen

in de css hoef je bij de de body geen font family toe te voegen, want dat wordt bij elk bestand al automatisch gedaan via de style.css.
