### ISSUE TITLE
Open hiring pagina aanmaken

### ISSUE THREAD

**Issue by Zoruasy** [justalana/tle1-ontwerpen#36]

**Comment by justalana** [comment]
je hoeft in het html bestand geen head neer te zetten want die wordt al via de site-layout ingeladen. je kan wel ff kijken bij andere pagina's hoe dat is gedaan. de css moet je dan bovenin de pagina even inladen

je kan eventueel de javascript in een apart bestandje zetten, hoeft niet per se want het werkt zo ook. maar voor volgende keer is dat misschien wat handiger
