### ISSUE TITLE
Demo feedback

### ISSUE THREAD

**Issue by justalana** [justalana/tle1-ontwerpen#39]
- [x] Formatting van vacature overzicht pagina titel fixen voor mobile view
- [x] Admin menu helemaal Nederlands maken
- [x] Werkzoekende naar de vacature overzicht pagina sturen na inloggen ipv dashboard
- [x] Werkgever en admin naar een dashboard sturen na het inloggen
- [ ] Bij toegang vragen naar pagina waar je niet heen mag geen unautherized error laten zien, maar rerouten naar de inlogpagina.
- [x] Contract duur bij vacature aanmaken niet in dagen zetten, maar in vaste contract waardes(6maanden, 1jaar, etc)
- [x] Alle bestaande CSS issues oplossen
- [ ] Presenteerbare dummy data in database
- [x] User flow toevoegen (navbar en footer etc)
- [ ] Toegankelijkheid checken

**Comment by Zoruasy** [comment]
Helleuw, volgens mij kan het aan mijn laptop liggen maar de button op de homepage "een vacature plaatsen"  geeft mij een 403 error. hij stuurt mij wel door naar vacanies create.
navbar zou in principe alleen aangepast worden met de contact pagina erin en de about-us. hij rederect mij ook niet via de homepage naar dashboard en profile als ik erop klik via de navbar. logout en vacatures wel :-)
