### ISSUE TITLE
Als werkgever wil ik een vacature overzicht kunnen zien van al mijn vacatures, zodat ik makkelijk kan zien welke vacatures ik heb openstaan

### ISSUE THREAD

**Issue by justalana** [justalana/tle1-ontwerpen#4]
Er is een pagina met een vacature overzicht met een knop voor het inzien, aanpassen, verwijderen en aan/uit zetten van de vacature

- [x] - Een knop naar de detailpagina
- [ ] - een knop voor de edit pagina
- [ ] - een knop om de vacature te verwijderen
- [ ] - een toggle om de vacature aan/uit te zetten

**Comment by Spooked2** [comment]
Een werkgever wil misschien de vacatures van andere werkgevers bekijken; niet om op te reageren, maar om te kijken wat de rest heeft gedaan. Weet niet zeker of dit een probleem is, kijk of je dit kan vragen aan de rest van het team.

Een branch kan meerdere users hebben, dit staat al goed in de huidige develop branch dus let op bij het mergen.

Ik heb zelf geprobeert om met Has te werken in een model, maar had nog geen success. Check even of het werkt in User.php, zo ja: hou het zo, zo nee: maak er een BelongsTo van

In de index van vacancies heb je nu een if statement gebruikt om te checken of de user een werkgever is. Dit kan en is geen probleem, maar in laravel kan je hier beter een gate voor gebruiken en een @can (Hier kan je nog steeds @else in gebruiken). Zie wat ik heb gedaan in de AppServiceProvider.php en de nav bar
