### ISSUE TITLE
dashboard werknemer

### ISSUE THREAD

**Issue by Zoruasy** [justalana/tle1-ontwerpen#43]

**Comment by Esse03** [comment]
Ik zie dat je nu een aparte class hebt voor authorisatie, dat is een stuk mooier en schoner, ik had daarbij wel de vraag waarom admin middleware is weggehaald, ik geloof dat dat niet helemaal de bedoeling is. Ik weet niet of ik overal voldoende verstand van heb om verder te helpen dus vooralsnog denk ik dat de breeze routes nu overbodig zijn, ook maak ik nog ff een klein aanvullinkie voor werkgever maar da's niet heel veel werk
