### ISSUE TITLE
Als werknemer wil ik mijn profiel kunnen aanpassen zodat ik informatie die wijzigt of niet langer relevant is kan updaten

### ISSUE THREAD

**Issue by justalana** [justalana/tle1-ontwerpen#5]
##DoD
- [x]  Werkt op verschillende browsers
- [x]  Is geschikt voor mobiele telefoon
- [x]  Voldoet aan de styleguide
- [x] Voldoet aan de code conventions
- [x] Routes en formulieren goed beveiligen
- [ ] Voldoet aan WACG level A

## Acceptatie criteria

- [x] - profiel kan aangepast worden
- [x] - Wachtwoord kunnen updaten
- [x] - E-mail kunnen updaten
- [x] - Werkend in de database
- [x] - Melding met dat het succesvol is ge-update

**Comment by AlexDusselaar** [comment]
functionaliteit is helemaal goed maar de css moet nog even aangepast worden naar de style guide. heb het ook even met sander en esse besproken en het is misschien makkelijker om dat op een nieuwe pagina te doen om breeze components te omzeilen maar ik stel voor dat we daar later even naar kijken met een aantal mensen van het team.
