### ISSUE TITLE
Als werkgever wil ik mijn vacatures kunnen aanpassen, zodat ik de informatie die ik heb gegeven kan aanpassen indien nodig

### ISSUE THREAD

**Issue by justalana** [justalana/tle1-ontwerpen#9]
Er is een pagina waar ik een vacature kan inzien met een knop om de vacature aan te passen

- [x] - een knop in het vacature overzicht
- [x] - een knop in het detailscherm 
- [x] - een edit pagina
- [x] - een confirmatie scherm met de aangepaste detailpagina

**Comment by Spooked2** [comment]
De preview is opgelost dankzij Trix omdat dat een WYSIWYG ding is (What You See Is What You Get)
